name: hotfix cherry-pick

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make new branch from main
        env:
          PR_BRANCH: auto-main-${{github.sha}}
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH" origin/main
          git cherry-pick --strategy=recursive -X ours "$GITHUB_SHA"
          git push -u origin "$PR_BRANCH"
      - name: merge new branch in main
        env:
          PR_BRANCH: auto-main-${{github.sha}}
        run: |
          git checkout main
          git merge "origin/$PR_BRANCH"
          git push origin main
          git push origin --delete $PR_BRANCH
