name: hotfix cherry-pick

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make new branch from main
        env:
          PR_BRANCH: auto-main-${{github.sha}}
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH" origin/main
          git cherry-pick --strategy=recursive -X theirs "$GITHUB_SHA"
          git push -u origin "$PR_BRANCH"
          git checkout origin/main
      - name: create pull request
        env:
          PR_BRANCH: auto-main-${{github.sha}}
          PR_TITLE: $(git log -1 --format="%s" ${{github.sha}})
        run: |
          login "$GITHUB_ACTOR"
          password "$GITHUB_TOKEN"
          hub pull-request -b main -h "$PR_BRANCH" -l -a "$GITHUB_ACTOR" -m "\"AUTO:$PR_TITLE\""
