name: hotfix cherry-pick

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: make new branch from main
        id: s1
        env:
          PR_BRANCH: auto-main-${{github.sha}}
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH"
          git cherry-pick $(git merge-base main prod)..prod
          git push -u origin "$PR_BRANCH"
          git checkout main
      - name: Reset promotion branch
        run: |
          git fetch origin auto-main-${{github.sha}}:auto-main-${{github.sha}}
          git reset --hard auto-main-${{github.sha}}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-main-${{github.sha}}
          delete-branch: true
          title: ${{ github.event.head_commit.message }}
          body: |
            - This `hotfix` branch is submitted to the `prod` branch
          labels: |
            Auto
            Hotfix
          assignees: ${{github.actor}}
