name: hotfix cherry-pick

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make new branch from main
        env:
          PR_BRANCH: auto-main-${{github.sha}}
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH" origin/main
          git cherry-pick --strategy=recursive -X theirs "$GITHUB_SHA"
          git push -u origin "$PR_BRANCH"
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
          echo "github_sha - env.GITHUB_SHA"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-main-${github.sha}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
