name: hotfix cherry-pick

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make new branch from main
        id: s1
        env:
          PR_BRANCH: auto-main-${{github.sha}}
        if: startsWith(github.event.head_commit.message, 'fix')
        run: |
          git config --global user.email "$GITBOT_EMAIL"
          git config --global user.name "$GITHUB_ACTOR"
          git remote update
          git fetch --all
          git checkout -b "$PR_BRANCH" origin/main
          git cherry-pick --strategy=recursive -X theirs "$GITHUB_SHA"
          git push -u origin "$PR_BRANCH"
          git checkout main
      - name: Reset promotion branch
        if: steps.s1.conclusion == 'success'
        run: |
          git fetch origin auto-main-${{github.sha}}:auto-main-${{github.sha}}
          git reset --hard auto-main-${{github.sha}}
      - name: Create Pull Request
        if: steps.s1.conclusion == 'success'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-main-${{github.sha}}
          delete-branch: true
          title: ${{ github.event.head_commit.message }}
          body: |
            **Auto created pull request**
            - This branch is **hotfix**, It's submitted to the `main` branch.
            - This is auto created PR from Hotfix PR(submitted to the `prod` branch)
          labels: |
            Auto created
            Hotfix
          assignees: ${{github.actor}}
      - name: Check outputs
        if: steps.s1.conclusion == 'success'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
